name:                almat-expo-parser
version:             0.1.0.0
github:              "githubuser/almat-expo-parser"
license:             GPL2
author:              "Luc Doebereiner"
maintainer:          "luc.doebereiner@gmail.com"
copyright:           "2019 Luc Doebereiner"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            ALMAT RC Exposition Parser
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/almat-expo-parser#readme>

dependencies:
- base >= 4.7 && < 5
- text
- mtl
- bytestring
- filepath
- directory
- conduit
- http-conduit
- html-conduit
- xml-conduit
- conduit-extra
- aeson
- aeson-pretty
- containers
- blaze-html
- pandoc
- yaml
- tagsoup
- MissingH
- vector

library:
  source-dirs: src

executables:
  almat-expo-parser-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-orphans
    dependencies:
    - almat-expo-parser

tests:
  almat-expo-parser-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -fno-warn-orphans
    dependencies:
    - almat-expo-parser
