Hi everyone,

I hope your all well. Sorry, for being a little quiet. I have been
(re)reading the ALMAT documentation (mainly of the iterations) and
some of your papers. I've also started writing a small app for
organizing my more conceptual reflections on the ALMAT
documentation. You can find that here:
https://git.iem.at/davidpirro/almat_luc/tree/master/text

Apart from that, I've been trying to collect more general talking
points. Things that came to mind while reading, observations,
problems, ideas etc. Here are the talking points in a org-mode-like
list:

* Form of documentation (of iterations)
** Going beyond the limits of the RC
** Types of material: 
   dialog, spoken/written language, reflection, media, concept, talk,
   critique, code, work description, technical documentation, description of events/workshops
** Finding forms for these types of materials
** What to do with all the dialogues?
anmerken wenn stil problematisch
** Who speaks?
** Fragments and missing contexts (introductions, glue etc).
*** TODO sticky note where missing
** The meaning of arrows. Network of annotations
** Forms particular to the practice of the artist (text<->speech for JR, e.g.)
* Types of publications
** Number, kind
* Material outside of RC
** Journal/conference papers
pdfs as objects in meta-expo
* Code/Algorithms
** How to integrate, how to access?
** How to experience (in Browser etc)? 
* Navigation of the documentation/publication
** As a project archive
** Network of concepts
** Main thread?
linearisierung? wie alles durchlesen? nach teilaspekten strukturieren (z.b. zeitachse, tabellarisch, metatext, kuratierte räume/teilaspekte) 
** Filtering, algorithmic restructuring, queries?
index
** As an "Exhibition" (spatial structure) with rooms etc 
how to create a map of docu, scope der doku zeigen, walkthrough wie artefakte gewachsen sind
** Searchable
* Issues/Problems
** Tone, critique issues
*** TODO postit where problamtic
** The concept of "apparatus" (also vs. machine)
** Language issues
*** fehlerliste: redundanz, negationen fehlend, füllwörter
*** TODO korrekturbeispiel machen
** DP/HHR reflection on practices with 
regard to central ALMAT concepts is missing somewhat.
*** wie praktiken/projekte mit hhr/dp resonieren, response to residencies
*** was hat sich für hhr/dp verändert and forschungsfragen m it hinblick auf praktiken/erfahrungen/residenzen
*** Interview zu Konzepten, CMJ interview
** Resume Ron, JR
* Central concepts
** Matter
** Contingency
** Affect
** Recursion/Iteration
** Code/Text
** Language
** Space
** Computation
** Agency
** Experimentation
** Speculation
** Body
** Analysis/Re-Synthesis
** Mechanic/Organic
** Machine/Apparatus
** Representation
** Entanglements

I look forward to seeing you on Saturday.

Best,
Luc
* Gespräch 7.12
** auswahl an gesprächen
** working document
** ausstellung
** simple tagging
** crawler, what can we get from rendered
** meta-discourse
** identify passage that don't seem publishable, e.g. "document class" expo jr iteration
** compositional process, the development of ways of creating rc expositions, differences between iterations
how did the documentation evolve

